DORI_BAZASI = {
  "enalapril": "💊 Enalapril: Qon bosimini tushiradi va yurak faoliyatini yengillashtiradi.",
  "amlodipin": "💊 Amlodipin: Qon tomirlarni kengaytirib bosimni pasaytiradi.",
  "kaptopril": "💊 Kaptopril: Tez ta’sir qiluvchi qon bosim dori vositasi.",
  "losartan": "💊 Losartan: Gipertoniyada ishlatiladi va buyrakni himoya qiladi.",
  "atenolol": "💊 Atenolol: Yurak urishini sekinlashtiradi va bosimni tushiradi.",
  "bisoprolol": "💊 Bisoprolol: Yurak yuklamasini kamaytiradi va pulsni pasaytiradi.",
  "nitroglitserin": "💊 Nitroglitserin: Yurak og‘rig‘ida tez yordam beradi.",
  "validol": "💊 Validol: Yengil tinchlantiruvchi va yurak bezovtaligida qo‘llanadi.",
  "digoksin": "💊 Digoksin: Yurak qisqarishini kuchaytiradi.",
  "varfarin": "💊 Varfarin: Qonni suyultirib tromb hosil bo‘lishini oldini oladi.",

  "klopidogrel": "💊 Klopidogrel: Tromblarni oldini oluvchi dori.",
  "atorvastatin": "💊 Atorvastatin: Xolesterinni kamaytiradi.",
  "simvastatin": "💊 Simvastatin: Yurak kasalliklari xavfini kamaytiradi.",
  "metformin": "💊 Metformin: Qondagi shakar miqdorini kamaytiradi.",
  "glibenklamid": "💊 Glibenklamid: Insulin ajralishini oshiradi.",
  "insulin": "💊 Insulin: Qandli diabetda glyukozani nazorat qiladi.",
  "levotiroksin": "💊 Levotiroksin: Qalqonsimon bez gormonini to‘ldiradi.",
  "merkazolil": "💊 Merkazolil: Qalqonsimon bez faoliyatini pasaytiradi.",
  "kalsiy_glyukonat": "💊 Kalsiy glyukonat: Kalsiy yetishmovchiligini to‘ldiradi.",
  "magniy_sulfat": "💊 Magniy sulfat: Spazmni kamaytiradi va tinchlantiradi.",

  "temir_preparatlari": "💊 Temir preparatlari: Kamqonlikni davolashda ishlatiladi.",
  "foliy_kislotasi": "💊 Foliy kislotasi: Qon hosil bo‘lishini yaxshilaydi.",
  "askorbin_kislotasi": "💊 Askorbin kislotasi: Immunitetni oshiradi.",
  "vitamin_d": "💊 Vitamin D: Suyaklarni mustahkamlaydi.",
  "multivitamin": "💊 Multivitamin: Organizmni umumiy qo‘llab-quvvatlaydi.",
  "diazepam": "💊 Diazepam: Tinchlantiruvchi va uyqu beruvchi dori.",
  "fenazepam": "💊 Fenazepam: Kuchli sedativ vosita.",
  "haloperidol": "💊 Haloperidol: Psixik kasalliklarda ishlatiladi.",
  "amitriptilin": "💊 Amitriptilin: Depressiyani davolaydi.",
  "fluoksetin": "💊 Fluoksetin: Kayfiyatni yaxshilovchi antidepressant.",

  "sertralin": "💊 Sertralin: Depressiya va xavotirni kamaytiradi.",
  "paroksetin": "💊 Paroksetin: Antidepressant va tinchlantiruvchi.",
  "karbamazepin": "💊 Karbamazepin: Tutqanoq kasalligida ishlatiladi.",
  "valproat": "💊 Valproat: Epilepsiyada qo‘llanadi.",
  "fenitoin": "💊 Fenitoin: Tutqanoqni oldini oladi.",
  "levetirasetam": "💊 Levetirasetam: Epilepsiya dorisi.",
  "gabapentin": "💊 Gabapentin: Nevrologik og‘riqlarda ishlatiladi.",
  "pregabalin": "💊 Pregabalin: Asab og‘rig‘ini kamaytiradi.",
  "meloksikam": "💊 Meloksikam: Yallig‘lanishga qarshi dori.",
  "nimesulid": "💊 Nimesulid: Og‘riq va yallig‘lanishni kamaytiradi.",

  "ketorol": "💊 Ketorol: Kuchli og‘riq qoldiruvchi.",
  "diklofenak": "💊 Diklofenak: Yallig‘lanishga qarshi vosita.",
  "indometasin": "💊 Indometasin: Bo‘g‘im og‘rig‘ida ishlatiladi.",
  "naproksen": "💊 Naproksen: Og‘riq va yallig‘lanishni kamaytiradi.",
  "tramadol": "💊 Tramadol: O‘rtacha kuchli og‘riq qoldiruvchi.",
  "morfiy": "💊 Morfiy: Juda kuchli og‘riq qoldiruvchi.",
  "lidokain": "💊 Lidokain: Mahalliy og‘riqsizlantiruvchi.",
  "novokain": "💊 Novokain: Lokal anesteziya uchun ishlatiladi.",
  "salbutamol": "💊 Salbutamol: Bronxlarni kengaytiradi.",
  "prednizolon": "💊 Prednizolon: Kuchli yallig‘lanishga qarshi gormon.",
  "pantoprazol": "💊 Pantoprazol: Reflyuks va yara kasalligida ishlatiladi.",
  "rabeprazol": "💊 Rabeprazol: Oshqozon kislotasini bostiradi.",
  "esomeprazol": "💊 Esomeprazol: Gastrit va GERDda samarali.",
  "ranitidin": "💊 Ranitidin: Kislota ishlab chiqarilishini kamaytiradi.",
  "famotidin": "💊 Famotidin: Oshqozon kislotasini kamaytiradi.",
  "almagel": "💊 Almagel: Oshqozonni himoya qiladi va kislotani neytrallaydi.",
  "maalox": "💊 Maalox: Kislotalikni kamaytiruvchi antasid.",
  "fosfalyugel": "💊 Fosfalyugel: Oshqozonni qoplaydi va himoya qiladi.",
  "de-nol": "💊 De-nol: Oshqozon yarasini davolashda ishlatiladi.",

  "pankreatin": "💊 Pankreatin: Ovqat hazmini yaxshilaydi.",
  "mezim": "💊 Mezim: Ferment yetishmovchiligida qo‘llanadi.",
  "kreon": "💊 Kreon: Oshqozon osti bezi fermenti.",
  "festal": "💊 Festal: Hazmni yaxshilovchi ferment dori.",
  "domperidon": "💊 Domperidon: Ko‘ngil aynishni kamaytiradi.",
  "metoklopramid": "💊 Metoklopramid: Qusishga qarshi dori.",
  "itoprid": "💊 Itoprid: Oshqozon harakatini yaxshilaydi.",
  "loperamid": "💊 Loperamid: Ich ketishni to‘xtatadi.",
  "enterol": "💊 Enterol: Ichak mikroflorasini tiklaydi.",
  "lineks": "💊 Lineks: Probiotik dori.",

  "bifidumbakterin": "💊 Bifidumbakterin: Ichak bakteriyalarini tiklaydi.",
  "hilak_forte": "💊 Hilak forte: Mikroflorani normallashtiradi.",
  "smekta": "💊 Smekta: Ich ketishda toksinlarni chiqaradi.",
  "regidron": "💊 Regidron: Suvsizlanishni oldini oladi.",
  "senade": "💊 Senade: Ichni suruvchi o‘simlik dori.",
  "dufalak": "💊 Dufalak: Ich qotishida ishlatiladi.",
  "bisakodil": "💊 Bisakodil: Ichak faoliyatini oshiradi.",
  "guttalaks": "💊 Guttalaks: Ich suruvchi tomchi.",
  "no_shpa": "💊 No-shpa: Spazmni kamaytiradi.",
  "papaverin": "💊 Papaverin: Mushaklarni bo‘shashtiradi.",

  "eufillin": "💊 Eufillin: Bronxlarni kengaytiradi.",
  "berodual": "💊 Berodual: Nafasni yengillashtiradi.",
  "ambroksol": "💊 Ambroksol: Balg‘amni suyultiradi.",
  "bromgeksin": "💊 Bromgeksin: Yo‘talni yengillashtiradi.",
  "acetilsistein": "💊 Atsetilsistein: Balg‘amni chiqaradi.",
  "lazolvan": "💊 Lazolvan: Nafas yo‘llarini tozalaydi.",
  "sinekod": "💊 Sinekod: Quruq yo‘talni to‘xtatadi.",
  "kodein": "💊 Kodein: Yo‘talni bostiradi.",
  "loratadin": "💊 Loratadin: Allergiyani kamaytiradi.",
  "desloratadin": "💊 Desloratadin: Antigistamin dori.",

  "ketotifen": "💊 Ketotifen: Allergiyani oldini oladi.",
  "suprastin": "💊 Suprastin: Allergiyaga qarshi vosita.",
  "tavegil": "💊 Tavegil: Qichishishni kamaytiradi.",
  "fenkarol": "💊 Fenkarol: Antigistamin dori.",
  "prednizolon": "💊 Prednizolon: Yallig‘lanishga qarshi gormon.",
  "deksametazon": "💊 Deksametazon: Kuchli steroid dori.",
  "gidrokortizon": "💊 Gidrokortizon: Allergiya va yallig‘lanishda ishlatiladi.",
  "betametazon": "💊 Betametazon: Teri kasalliklarida qo‘llanadi.",
  "salbutamol": "💊 Salbutamol: Astmada ishlatiladi.",
  "montelukast": "💊 Montelukast: Allergik astmada qo‘llanadi.",
  "amoksiklav": "💊 Amoksiklav: Antibiotik bo‘lib, bakterial infeksiyalarni davolaydi.",
  "augmentin": "💊 Augmentin: Keng ta’sirli antibiotik kombinatsiyasi.",
  "sefazolin": "💊 Sefazolin: Inyeksion antibiotik, og‘ir infeksiyalarda ishlatiladi.",
  "sefuroksim": "💊 Sefuroksim: Nafas yo‘llari infeksiyalarida qo‘llanadi.",
  "sefotaksim": "💊 Sefotaksim: Kuchli antibiotik vosita.",
  "seftazidim": "💊 Seftazidim: Gram-manfiy bakteriyalarga qarshi ishlatiladi.",
  "sefepim": "💊 Sefepim: Keng ta’sirli antibiotik.",
  "imipenem": "💊 Imipenem: Og‘ir infeksiyalarda qo‘llanadi.",
  "meropenem": "💊 Meropenem: Kuchli antibakterial dori.",
  "vankomitsin": "💊 Vankomitsin: Og‘ir bakterial infeksiyalarda ishlatiladi.",

  "linezolid": "💊 Linezolid: Antibiotik, rezistent bakteriyalarga qarshi.",
  "rifampitsin": "💊 Rifampitsin: Sil kasalligida ishlatiladi.",
  "izoniazid": "💊 Izoniazid: Tuberkulyozni davolaydi.",
  "etambutol": "💊 Etambutol: Silga qarshi dori.",
  "pirazinamid": "💊 Pirazinamid: Tuberkulyoz terapiyasida ishlatiladi.",
  "flukonazol": "💊 Flukonazol: Zamburug‘larga qarshi dori.",
  "itrakonazol": "💊 Itrakonazol: Mikozlarni davolaydi.",
  "nistatin": "💊 Nistatin: Kandidozda qo‘llanadi.",
  "klotrimazol": "💊 Klotrimazol: Zamburug‘ga qarshi krem.",
  "terbinafin": "💊 Terbinafin: Teri zamburug‘larida ishlatiladi.",

  "asiklovir": "💊 Asiklovir: Virusga qarshi dori.",
  "valasiklovir": "💊 Valasiklovir: Gerpesda qo‘llanadi.",
  "oseltamivir": "💊 Oseltamivir: Gripp virusiga qarshi dori.",
  "interferon": "💊 Interferon: Immun tizimini kuchaytiradi.",
  "ribavirin": "💊 Ribavirin: Viruslarga qarshi vosita.",
  "metformin": "💊 Metformin: Qand miqdorini kamaytiradi.",
  "gliklazid": "💊 Gliklazid: Diabetda ishlatiladi.",
  "sitagliptin": "💊 Sitagliptin: Qandni nazorat qiladi.",
  "dapagliflozin": "💊 Dapagliflozin: Glyukozani chiqarishni oshiradi.",
  "empagliflozin": "💊 Empagliflozin: Diabetda qo‘llanadi.",

  "levotiroksin": "💊 Levotiroksin: Qalqonsimon bez gormoni.",
  "tiamazol": "💊 Tiamazol: Qalqonsimon bez faoliyatini pasaytiradi.",
  "prednizolon": "💊 Prednizolon: Steroid yallig‘lanishga qarshi dori.",
  "deksametazon": "💊 Deksametazon: Kuchli gormonal vosita.",
  "metilprednizolon": "💊 Metilprednizolon: Allergiya va yallig‘lanishda ishlatiladi.",
  "insulin_glargin": "💊 Insulin glargin: Uzoq ta’sirli insulin turi.",
  "insulin_aspart": "💊 Insulin aspart: Tez ta’sir qiluvchi insulin.",
  "heparin": "💊 Heparin: Qonni suyultiradi.",
  "enoksaparin": "💊 Enoksaparin: Trombozga qarshi vosita.",
  "varfarin": "💊 Varfarin: Qon ivishini kamaytiradi.",

  "atorvastatin": "💊 Atorvastatin: Xolesterinni kamaytiradi.",
  "rosuvastatin": "💊 Rosuvastatin: Yurak kasalliklarida ishlatiladi.",
  "simvastatin": "💊 Simvastatin: Xolesterinni pasaytiradi.",
  "ezetimib": "💊 Ezetimib: Xolesterin so‘rilishini kamaytiradi.",
  "nitroglitserin": "💊 Nitroglitserin: Yurak og‘rig‘ida qo‘llanadi.",
  "izosorbid_dinitrat": "💊 Izosorbid dinitrat: Yurak qon tomirlarini kengaytiradi.",
  "verapamil": "💊 Verapamil: Yurak ritmini tartibga soladi.",
  "diltiazem": "💊 Diltiazem: Qon bosimini tushiradi.",
  "amiodaron": "💊 Amiodaron: Aritmiyada ishlatiladi.",
  "lidokain": "💊 Lidokain: Mahalliy og‘riqsizlantiruvchi.",
  "novokain": "💊 Novokain: Mahalliy og‘riqsizlantiruvchi vosita.",
  "artikain": "💊 Artikain: Stomatologiyada ishlatiladigan anestezik.",
  "bupivakain": "💊 Bupivakain: Uzoq ta’sirli lokal anesteziya.",
  "ketamin": "💊 Ketamin: Umumiy narkoz uchun ishlatiladi.",
  "propofol": "💊 Propofol: Tez ta’sir qiluvchi narkoz dori.",
  "tiopental": "💊 Tiopental: Anesteziyada qo‘llanadi.",
  "midazolam": "💊 Midazolam: Tinchlantiruvchi va uyqu beruvchi.",
  "zolpidem": "💊 Zolpidem: Uyqusizlikda ishlatiladi.",
  "melatonin": "💊 Melatonin: Uyquni tartibga soladi.",
  "fenobarbital": "💊 Fenobarbital: Tutqanoqda ishlatiladi.",

  "karbamazepin": "💊 Karbamazepin: Epilepsiyada qo‘llanadi.",
  "valproat": "💊 Valproat: Tutqanoqni kamaytiradi.",
  "fenitoin": "💊 Fenitoin: Epilepsiya dorisi.",
  "levetirasetam": "💊 Levetirasetam: Nevrologik kasalliklarda ishlatiladi.",
  "gabapentin": "💊 Gabapentin: Asab og‘rig‘ini kamaytiradi.",
  "pregabalin": "💊 Pregabalin: Nevropatik og‘riqlarda ishlatiladi.",
  "baklofen": "💊 Baklofen: Mushak spazmini kamaytiradi.",
  "tolperizon": "💊 Tolperizon: Mushaklarni bo‘shashtiradi.",
  "tizanidin": "💊 Tizanidin: Spazmolitik vosita.",
  "piratsetam": "💊 Piratsetam: Miya faoliyatini yaxshilaydi.",

  "fenotropil": "💊 Fenotropil: Aqliy faoliyatni oshiradi.",
  "glitsin": "💊 Glitsin: Asab tizimini tinchlantiradi.",
  "cinnarizin": "💊 Cinnarizin: Qon aylanishini yaxshilaydi.",
  "betagistin": "💊 Betagistin: Bosh aylanishida qo‘llanadi.",
  "mexidol": "💊 Mexidol: Antioksidant va neyroprotektor.",
  "aktovegin": "💊 Aktovegin: To‘qima oziqlanishini yaxshilaydi.",
  "mildronat": "💊 Mildronat: Energiya almashinuvini yaxshilaydi.",
  "trimetazidin": "💊 Trimetazidin: Yurakni himoya qiladi.",
  "riboksin": "💊 Riboksin: Metabolik dori.",
  "adenozin": "💊 Adenozin: Yurak ritmini tiklaydi.",

  "salbutamol": "💊 Salbutamol: Bronxlarni kengaytiradi.",
  "fenoterol": "💊 Fenoterol: Nafasni yengillashtiradi.",
  "ipratropium": "💊 Ipratropium: Bronxospazmni kamaytiradi.",
  "budesonid": "💊 Budesonid: Yallig‘lanishga qarshi inhalyatsion dori.",
  "flutikazon": "💊 Flutikazon: Astmada qo‘llanadi.",
  "montelukast": "💊 Montelukast: Allergik astmada ishlatiladi.",
  "loratadin": "💊 Loratadin: Allergiyani kamaytiradi.",
  "setirizin": "💊 Setirizin: Antigistamin vosita.",
  "desloratadin": "💊 Desloratadin: Allergiyaga qarshi dori.",
  "levosetirizin": "💊 Levosetirizin: Kuchli antigistamin.",

  "suprastin": "💊 Suprastin: Allergik reaksiyada ishlatiladi.",
  "tavegil": "💊 Tavegil: Qichishishni kamaytiradi.",
  "fenkarol": "💊 Fenkarol: Allergiyaga qarshi vosita.",
  "adrenalin": "💊 Adrenalin: Shok holatida ishlatiladi.",
  "dopamin": "💊 Dopamin: Qon bosimini oshiradi.",
  "noradrenalin": "💊 Noradrenalin: Tomirlarni toraytiradi.",
  "atropin": "💊 Atropin: Yurak urishini tezlashtiradi.",
  "pilokarpin": "💊 Pilokarpin: Ko‘z bosimini kamaytiradi.",
  "timolol": "💊 Timolol: Glaukomada ishlatiladi.",
  "latanoprost": "💊 Latanoprost: Ko‘z ichki bosimini tushiradi.",
  "oksitotsin": "💊 Oksitotsin: Bachadon qisqarishini kuchaytiradi.",
  "misoprostol": "💊 Misoprostol: Bachadon faoliyatini oshiradi.",
  "klomifen": "💊 Klomifen: Ovulyatsiyani rag‘batlantiradi.",
  "estradiol": "💊 Estradiol: Ayol gormoni o‘rnini bosadi.",
  "progesteron": "💊 Progesteron: Homiladorlikni saqlashda ishlatiladi.",
  "testosteron": "💊 Testosteron: Erkak gormoni yetishmovchiligida qo‘llanadi.",
  "finasterid": "💊 Finasterid: Prostata kattalashuvini kamaytiradi.",
  "tamsulozin": "💊 Tamsulozin: Siydik chiqishini yengillashtiradi.",
  "sildenafil": "💊 Sildenafil: Erektil disfunktsiyada ishlatiladi.",
  "tadalafil": "💊 Tadalafil: Uzoq ta’sirli potensiya dorisi.",

  "asetazolamid": "💊 Asetazolamid: Diuretik va glaukomada qo‘llanadi.",
  "spironolakton": "💊 Spironolakton: Kaliy tejovchi diuretik.",
  "gidroxlorotiazid": "💊 Gidroxlorotiazid: Qon bosimini tushiradi.",
  "indapamid": "💊 Indapamid: Diuretik va gipertoniya dorisi.",
  "mannitol": "💊 Mannitol: Miya shishida ishlatiladi.",
  "allopurinol": "💊 Allopurinol: Podagrada siydik kislotasini kamaytiradi.",
  "kolxisin": "💊 Kolxisin: Podagra xurujida ishlatiladi.",
  "metotreksat": "💊 Metotreksat: Autoimmun kasalliklarda qo‘llanadi.",
  "azatioprin": "💊 Azatioprin: Immunitetni pasaytiradi.",
  "siklosporin": "💊 Siklosporin: Transplantatsiyada ishlatiladi.",

  "takrolimus": "💊 Takrolimus: Kuchli immunosupressiv vosita.",
  "levodopa": "💊 Levodopa: Parkinson kasalligida ishlatiladi.",
  "selegilin": "💊 Selegilin: Parkinson simptomlarini kamaytiradi.",
  "ropinirol": "💊 Ropinirol: Dopamin agonisti.",
  "donepezil": "💊 Donepezil: Altsgeymerda qo‘llanadi.",
  "memantin": "💊 Memantin: Kognitiv funksiyani yaxshilaydi.",
  "sumatriptan": "💊 Sumatriptan: Migren xurujini to‘xtatadi.",
  "zolmitriptan": "💊 Zolmitriptan: Migren uchun dori.",
  "ergotamin": "💊 Ergotamin: Bosh og‘rig‘ida ishlatiladi.",
  "kofein": "💊 Kofein: Markaziy nerv tizimini stimulyatsiya qiladi.",

  "nikotin_patch": "💊 Nikotin patch: Chekishni tashlashga yordam beradi.",
  "bupropion": "💊 Bupropion: Antidepressant va chekishni tashlashda ishlatiladi.",
  "vareniklin": "💊 Vareniklin: Nikotin qaramligini kamaytiradi.",
  "disulfiram": "💊 Disulfiram: Spirtli ichimlikka qarshi dori.",
  "nalokson": "💊 Nalokson: Opioid zaharlanishida ishlatiladi.",
  "metadon": "💊 Metadon: Opioid qaramlikni davolaydi.",
  "buprenorfin": "💊 Buprenorfin: Qaramlik terapiyasida qo‘llanadi.",
  "ondansetron": "💊 Ondansetron: Qusishga qarshi kuchli vosita.",
  "aprepitant": "💊 Aprepitant: Kimyoterapiyada qusishni oldini oladi.",
  "dimenhidrinat": "💊 Dimenhidrinat: Harakat kasalligida ishlatiladi.",

  "skopolamin": "💊 Skopolamin: Ko‘ngil aynishni kamaytiradi.",
  "laktuloza": "💊 Laktuloza: Ich qotishini davolaydi.",
  "bisakodil": "💊 Bisakodil: Ichni suruvchi vosita.",
  "senna": "💊 Senna: O‘simlik asosli ich suruvchi.",
  "polietilenglikol": "💊 Polietilenglikol: Ichni yumshatadi.",
  "simetikon": "💊 Simetikon: Qorin dam bo‘lishini kamaytiradi.",
  "pankreatin": "💊 Pankreatin: Ovqat hazmini yaxshilaydi.",
  "ursodeoksixolat": "💊 Ursodeoksixolat: Jigar va o‘t yo‘llarida ishlatiladi.",
  "silymarin": "💊 Silymarin: Jigarni himoya qiladi.",
  "ademetionin": "💊 Ademetionin: Jigar faoliyatini yaxshilaydi.",
"metformin": "💊 Metformin: Qandli diabetda qon shakarini tushirish uchun qo‘llaniladi.",
    "amoksitsillin": "💊 Amoksitsillin: Keng ko‘lamli antibakterial dori (antibiotik).",
    "azitromitsin": "💊 Azitromitsin: Nafas yo‘llari va boshqa infeksiyalarda qo‘llaniladigan antibiotik.",
    "kaptopril": "💊 Kaptopril: Gipertoniya (yuqori qon bosimi)da tez yordam beruvchi dori.",
    "bisoprolol": "💊 Bisoprolol: Yurak urishini sekinlashtiradi va qon bosimini tushiradi.",
    "deksametazon": "💊 Deksametazon: Kuchli yallig‘lanishga qarshi va allergiyaga qarshi gormonal dori.",
    "diklofenak": "💊 Diklofenak: Bo‘g‘im va mushak og‘riqlarida yallig‘lanishga qarshi vosita.",
    "no-shpa": "💊 No-shpa (Drotaverin): Silliq mushaklar spazmini (og‘rig‘ini) yo‘qotadi.",
    "gepabene": "💊 Gepabene: O‘t haydovchi va jigarni himoya qiluvchi o‘simlik preparati.",
    "kanefron": "💊 Kanefron: Buyrak va siydik yo‘llari kasalliklarida qo‘llaniladi.",
    "omeprazol": "💊 Omeprazol: Oshqozon kislotasini kamaytiradi, gastrit va yara kasalligida qo‘llaniladi.",
    "pantoprazol": "💊 Pantoprazol: Reflyuks va oshqozon-ichak yara kasalliklarida samarali vosita.",
    "ranitidin": "💊 Ranitidin: Me’da shirasining kislotaliligini pasaytiruvchi dori.",
    "almagel": "💊 Almagel: Jig‘ildon qaynashi va oshqozon og‘rig‘ida kislotani neytrallaydi.",
    "mezym": "💊 Mezym (Pankreatin): Ovqat hazm qilishni yaxshilovchi ferment preparati.",
    "festal": "💊 Festal: Ovqat hazm qilish va o‘t haydash jarayonini yaxshilaydi.",
    "lineks": "💊 Lineks: Ichak mikroflorasini tiklovchi probiotik.",
    "lopedium": "💊 Lopedium (Loperamid): Ich ketishini (diareya) to‘xtatish uchun qo‘llaniladi.",
    "regidron": "💊 Regidron: Kuchli ich ketishi va qusishda organizmdagi suv-tuz balansini tiklaydi.",
    "sero-papaverin": "💊 Sero-papaverin: Silliq mushaklar spazmini bo‘shashtiruvchi vosita.",
    "veroshpiron": "💊 Veroshpiron: Kaliyni saqlab qoluvchi peshob haydovchi dori.",
    "furosemid": "💊 Furosemid: Kuchli peshob haydovchi, shishlarga qarshi qo‘llaniladi.",
    "spazmalgon": "💊 Spazmalgon: Ham spazmni yechadi, ham og‘riqni qoldiradi.",
    "ketonal": "💊 Ketonal (Ketoprofen): Kuchli og‘riq qoldiruvchi va yallig‘lanishga qarshi vosita.",
    "nimesil": "💊 Nimesil: Isitma tushiruvchi va o‘tkir og‘riqlarni qoldiruvchi kukun.",
    "mukaltin": "💊 Mukaltin: Balg‘am ko‘chiruvchi o‘simlik preparati.",
    "ambrokso": "💊 Ambroksol: Balg‘amni suyultiradi va nafas yo‘llarini tozalaydi.",
    "loratadin": "💊 Loratadin: Allergiya alomatlarini (aksirish, qichishish) bartaraf etadi.",
    "yodomarin": "💊 Yodomarin: Qalqonsimon bez kasalliklarining oldini olish va davolash uchun yod preparati.",
    "yod-balans": "💊 Yod-balans: Organizmda yod tanqisligini to‘ldiradi, buqoq kasalligida qo‘llaniladi.",
    "l-tiroksin": "💊 L-tiroksin: Qalqonsimon bez gormoni yetishmovchiligida o‘rin bosuvchi dori sifatida beriladi.",
    "kardiomagnil": "💊 Kardiomagnil: Yurak xuruji (infarkt) va insultning oldini olish uchun qonni suyultiruvchi vosita.",
    "trombo-ass": "💊 Trombo-ass: Aspirin asosidagi dori, tromblar hosil bo‘lishidan himoya qiladi.",
    "konkor": "💊 Konkor (Bisoprolol): Yuqori qon bosimi va yurak ritmi buzilishida qo‘llaniladi.",
    "valeriana": "💊 Valeriana (Valeryanka): Tinchlantiruvchi, uyquni yaxshilovchi o‘simlik preparati.",
    "glitsin": "💊 Glitsin: Miyadagi moddalar almashinuvini yaxshilaydi, stress va hayajonni kamaytiradi.",
    "askorutin": "💊 Askorutin: Tomirlar devorini mustahkamlaydi va qon ketish moyilligini kamaytiradi.",
    "kalsiy-d3-nikomed": "💊 Kalsiy-D3 Nikomed: Suyaklarni mustahkamlaydi, osteoporozning oldini oladi.",
    "magne-b6": "💊 Magne B6: Asab tizimini tinchlantiradi va mushak tortishishlarida (sudorgi) yordam beradi.",
    "ferrum-lek": "💊 Ferrum Lek: Qon tarkibidagi temir moddasini oshiradi va anemiyani (kamqonlik) davolaydi.",
    "sorbifer": "💊 Sorbifer Durules: Temir tanqisligi anemiyasida qo‘llaniladigan samarali dori.",
    "aspartam": "💊 Aspartam (Panangin): Yurak mushagi uchun zarur bo‘lgan kaliy va magniy manbai.",
    "essensiale-forte": "💊 Essensiale Forte: Jigar hujayralarini tiklovchi va himoya qiluvchi dori.",
    "karsil": "💊 Karsil: Jigar faoliyatini yaxshilovchi, toksinlardan himoya qiluvchi o‘simlik dori.",
    "alloxol": "💊 Alloxol: O‘t haydovchi va ovqat hazm qilishni yaxshilovchi vosita.",
    "levomitsetin": "💊 Levomitsetin: Kuchli antibiotik, asosan ichak infeksiyalarida qo‘llaniladi.",
    "ersefuril": "💊 Ersefuril (Nifuroksazid): Ichakdagi infeksiyalarga qarshi dori, ich ketishida beriladi.",
    "mezim": "💊 Mezim: Ovqat hazm qilishni yaxshilovchi fermentlar majmuasi.",
    "kreon": "💊 Kreon: Me’da osti bezi faoliyati yetishmovchiligida qo‘llaniladi.",
    "festal": "💊 Festal: Ovqat hazm qilishni va o‘t ajralishini yaxshilaydi.",
    "motilium": "💊 Motilium: Ko‘ngil aynishi va qayt qilishni to‘xtatuvchi vosita.",
    "tserukal": "💊 Tserukal: Kuchli qayt qilish va jig‘ildon qaynashiga qarshi dori.",
    "duspatalin": "💊 Duspatalin: Ichaklardagi og‘riq va spazmlarni yo‘qotuvchi dori.",
    "trimedat": "💊 Trimedat: Ichak motorikasini tartibga soluvchi vosita.",
    "detraleks": "💊 Detraleks: Varikoz va gemorroyda tomirlar devorini mustahkamlaydi.",
    "flebodiya": "💊 Flebodiya: Venoz yetishmovchilikni davolash uchun qo‘llaniladi.",
    "kardiomagnil": "💊 Kardiomagnil: Qonni suyultiruvchi va trombdan himoya qiluvchi vosita.",
    "valokordin": "💊 Valokordin: Yurak sohasidagi og‘riqlarda va hayajonlanishda tinchlantiruvchi.",
    "korvalol": "💊 Korvalol: Tinchlantiruvchi va yurak tomirlarini kengaytiruvchi tomchi.",
    "trental": "💊 Trental: Tomirlarda qon aylanishini yaxshilovchi dori.",
    "aktoverin": "💊 Aktovegin: To‘qimalarda moddalar almashinuvini va tiklanishni tezlashtiradi.",
    "piratsetam": "💊 Piratsetam: Miyada qon aylanishini va xotirani yaxshilovchi nootrop vosita.",
    "ergoferon": "💊 Ergoferon: Viruslarga qarshi va immunitetni kuchaytiruvchi dori.",
    "anaferon": "💊 Anaferon: Shamollash va grippni oldini olish va davolash uchun.",
    "viferon": "💊 Viferon: Infeksion va yallig‘lanish kasalliklarida qo‘llaniladigan shamchalar.",
    "teraflyu": "💊 Teraflyu: Shamollash alomatlarini (isitma, burun bitishi) tezda bartaraf etuvchi kukun.",
    "koldreks": "💊 Koldreks: Gripp va o‘tkir shamollashga qarshi samarali ichimlik.",
    "insti": "💊 Insti: Shamollashda qo‘llaniladigan o‘simlik asosidagi kukun.",
    "sinupret": "💊 Sinupret: Burun bo‘shlig‘i yallig‘lanishi (gaymorit)da yordam beradi.",
    "pinozol": "💊 Pinozol: Burun bitishida ishlatiladigan moyli tomchi.",
    "otrivin": "💊 Otrivin: Burun shilliq qavati shishini kamaytiradi va nafasni ochadi.",
    "nazivin": "💊 Nazivin: Tumovda burun tomirlarini toraytiruvchi vosita.",
    "isla-moos": "💊 Isla-moos: Tomoq og‘rig‘i va ovoz bo‘g‘ilishida shimib yuriladigan dori.",
    "septolete": "💊 Septolete: Tomoqdagi mikroblarni o‘ldiradi va og‘riqni qoldiradi.",
    "lizobakt": "💊 Lizobakt: Og‘iz bo‘shlig‘i va tomoq kasalliklarida qo‘llaniladigan antiseptik.",
    "faringosept": "💊 Faringosept: Tomoqdagi bakteriyalarga qarshi shimuvchi dori.",
    "geksoral": "💊 Geksoral: Tomoq va og‘iz yallig‘lanishiga qarshi sprey.",
    "ingalipt": "💊 Ingalipt: Tomoq og‘rig‘ida antiseptik va yallig‘lanishga qarshi sprey.",
    "lyugol": "💊 Lyugol: Tomoqni artish yoki sepish uchun yodli antiseptik.",
    "furatsilin": "💊 Furatsilin: Tomoqni chayish va jarohatlarni yuvish uchun mikrobga qarshi vosita.",
    "pentalgin": "💊 Pentalgin: Beshta komponentdan iborat kuchli og‘riq qoldiruvchi va isitma tushiruvchi dori.",
    "tempalgin": "💊 Tempalgin: Kuchli og‘riqlarni qoldiradi va tinchlantiruvchi ta’sirga ega.",
    "solpadein": "💊 Solpadein: Migren, tish va mushak og‘riqlarida samarali yordam beradi.",
    "efferalgan": "💊 Efferalgan: Paratsetamol asosidagi dori, isitma va og‘riqni qoldiradi.",
    "nurofen": "💊 Nurofen (Ibuprofen): Bolalar va kattalar uchun isitma tushiruvchi hamda yallig‘lanishga qarshi dori.",
    "mig-400": "💊 Mig-400 (Ibuprofen): Tez ta’sir qiluvchi og‘riq qoldiruvchi vosita.",
    "askofren": "💊 Askofren: Bosh og‘rig‘i va gripp alomatlarida qo‘llaniladi.",
    "itomed": "💊 Itomed: Oshqozon motorikasini yaxshilaydi, ko‘ngil aynishi va qayt qilishda foydali.",
    "ganaton": "💊 Ganaton: Oshqozon-ichak trakti faoliyatini tartibga soladi.",
    "de-nol": "💊 De-Nol: Oshqozon va o‘n ikki barmoqli ichak yarasini davolashda ishlatiladi.",
    "hilak-forte": "💊 Hilak Forte: Ichak mikroflorasini tiklovchi va hazm qilishni yaxshilovchi tomchi.",
    "enterosgel": "💊 Enterosgel: Organizmdan toksinlar va zararli moddalarni chiqarib tashlovchi kuchli sorbent.",
    "smekta": "💊 Smekta: Jig‘ildon qaynashi, shish va ich ketishida qo‘llaniladigan dori.",
    "aktivatsiyalangan-ugol": "💊 Aktivatsiyalangan ugol: Zaharlanishda va ichakdagi gazlarni kamaytirishda ishlatiladi.",
    "laktofiltrum": "💊 Laktofiltrum: Ham ichakni tozalaydi, ham mikroflorani yaxshilaydi.",
    "bifidumbakterin": "💊 Bifidumbakterin: Ichak florasini sog‘lom bakteriyalar bilan boyitadi.",
    "dyufalak": "💊 Dyufalak: Ich qotishida (qabziyatda) qo‘llaniladigan yumshoq laksativ.",
    "bisakodil": "💊 Bisakodil: Surunkali ich qotishida yordam beruvchi dori."
}
